# action.yml
name: 'Update controls file'
description: 'Greet someone and record the time'
inputs:
  filename:  
    description: 'controls_<projectname>.txt'
    required: true
    default: 'controls_local.txt'
  directory: 
    description: 'directory where to search for files. Default is FHEM'
    required: false
    default: 'FHEM'
  extension: 
    description: 'Extension to include. Default is .pm'
    required: false
    default: '.pm'
  writemode: 
    description: 'Append (a) or overwrite (w) mode for controls file'
    required: false
    default: 'w'
outputs:
  controls_content: 
    description: 'If controls file was written'
runs:
  using: 'node12'
  main: 'dist/index.js'