# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  filename:  
    description: '<projectname>_controls.txt'
    required: true
    default: 'local_controls.txt'
outputs:
  time: # id of output
    result: 'If controls file was written'
runs:
  using: 'node12'
  main: 'main.js'
  args:
    - ${{ inputs.filename }}
    - 'FHEM'
    - '.pm'
